// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBBr-XW4pMlbwaWQZcirZjH_FHlTvU1Z8',
    appId: '1:1047427527252:web:fe446beb6676d20563f3c1',
    messagingSenderId: '1047427527252',
    projectId: 'to-do-f2fe7',
    authDomain: 'to-do-f2fe7.firebaseapp.com',
    storageBucket: 'to-do-f2fe7.firebasestorage.app',
    measurementId: 'G-VJ8MTYYXLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_TB-xdzGVmkOKOdoMtpAe1Km4WZ00ucE',
    appId: '1:1047427527252:android:945424267682e72063f3c1',
    messagingSenderId: '1047427527252',
    projectId: 'to-do-f2fe7',
    storageBucket: 'to-do-f2fe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-8wRkeNpbBkemMd92S3hR6D39wBRej5M',
    appId: '1:1047427527252:ios:97ef9f9895c9b69463f3c1',
    messagingSenderId: '1047427527252',
    projectId: 'to-do-f2fe7',
    storageBucket: 'to-do-f2fe7.firebasestorage.app',
    iosBundleId: 'com.example.architecture',
  );
}
